version: '2.2'

networks:
  br_mgmt:
    external:
      name: br-mgmt

services:
  region-controller:
    image: region:latest
    container_name: region
    restart: always
    networks:
      br_mgmt:
         ipv4_address: 192.168.110.235
    hostname: region.maas
    privileged: true

  rack-controller:
    image: rack:latest
    container_name: rack
    restart: always
    networks:
      br_mgmt:
         ipv4_address: 192.168.110.236
    hostname: rack.maas
    privileged: true

  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=maas
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=maasd
    networks:
      br_mgmt:
         ipv4_address: 192.168.110.237
    hostname: postgres.maas

